### ISSUE TITLE
Can I use Web Fonts with JCK Editor

### ISSUE THREAD

**Issue by theseedsower** [webfonts/Web-Fonts#13]
I have no idea what I'm doing. Can you please explain how to use the fonts?

**Comment by webfonts** [comment]
Hello! The extension will work with JCK, however it's not designed for end user use, but rather for web designers.  Fonts are assigned via CSS rules and you need a base understanding of CSS and HTML in order to employ it successfully.

You can get an idea of the workflow by watching the screencast: http://www.youtube.com/watch?v=GCk91vAmBRI
