### ISSUE TITLE
webfonts in joomla 1.5?

### ISSUE THREAD

**Issue by chulerico** [webfonts/Web-Fonts#16]
Hi,
I have a website on joomla 1.5 and I would like to use webfonts.

Is it the extension available for this version yet?

many thanks in advance...

**Comment by webfonts** [comment]
Hi Chulerico,

Unfortunately it's not available for 1.5 and won't be developed for 1.5  
because that version has reached end of life.

Sorry!

J

From: chulerico notifications@github.com on Fri, 09 Nov 2012 23:13:27  
+0900

> Hi,
> I have a website on joomla 1.5 and I would like to use webfonts.
> 
> Is it the extension available for this version yet?
> 
> many thanks in advance...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/16

## 

John Hooley
Blue Bridge Development
(503) 893-9181
http://bluebridgedev.com

**Comment by chulerico** [comment]
Hi,
thanks anyway, I updated the versoin and I am trying the extension right now. It seems to work fine!!
thank you very much

**Comment by webfonts** [comment]
Glad you like it :)

From: chulerico notifications@github.com on Mon, 19 Nov 2012 21:39:07  
+0900

> Hi,
> thanks anyway, I updated the versoin and I am trying the extension right  
> now. It seems to work fine!!
> thank you very much
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/16#issuecomment-10511988

## 

John Hooley
Blue Bridge Development
(503) 893-9181
http://bluebridgedev.com
