### ISSUE TITLE
web fonts won't display

### ISSUE THREAD

**Issue by Bandolin** [webfonts/Web-Fonts#2]
I don't know if its my template that is over riding the web fonts, but no matter what selector I add, and I've added just about everyone I could find using firebug, the text is still displaying Verdana instead of Amino from Google fonts.

I just can't get it to work. I followed the youtube video to the letter. The component is installed and the plugin is active. I've added the selectors but yet the font simply won't display in either firefox, explorer or even chrome.

Here is a link to my site www.flagtech.bandolin.net

**Comment by webfonts** [comment]
Hey Bandolin,

I believe that it has something to do with the design of your template.  
Could you disable the plugin and email a view source of the main landing  
page (So that I can see the HTML markup being created by the template)?

Thanks,

John

From: Bandolin  
reply@reply.github.com  
on Thu, 05 Jan 2012 19:45:44 -0500

> I don't know if its my template that is over riding the web fonts, but  
> no matter what selector I add, and I've added just about everyone I  
> could find using firebug, the text is still displaying Verdana instead  
> of Amino from Google fonts.
> 
> I just can't get it to work. I followed the youtube video to the letter.  
> The component is installed and the plugin is active. I've added the  
> selectors but yet the font simply won't display in either firefox,  
> explorer or even chrome.
> 
> Here is a link to my site www.flagtech.bandolin.net
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/2

## 

John Hooley
Blue Bridge Development
(503) 893-9181
http://bluebridgedev.com
