### ISSUE TITLE
Fonts from Fonts.com aren't added

### ISSUE THREAD

**Issue by BorderC** [webfonts/Web-Fonts#26]
I have been using your great extension on many sites without any major problems, but have run in to problems on a new site I am developing. 

I have added the project on Fonts.com including the url - and have selected a number of fonts. Still, the selected fonts won't turn up in the web fonts stylesheet.

I have a font from Google Fonts added on the site, and it publishes and works ok.

Are you able to help me locate the cause of the problem? Thank you very much in advance.

Greetings,

Chris

**Comment by kamescg** [comment]
I am also having this same issue.

The current website project I am on has to have this function work, so I will post when I find a solution.

**Comment by BorderC** [comment]
Hi KamesG, thanks for your comment. I'd really appreciate any advise I can get, as I'am experiencing all sorts of issues with Web Fonts and fonts.com. Basically, after working well in the past, something seems to be wrong with the connection between my site and fonts.com. Experienced issues are:
- can't install new fonts from Web Fonts
- selector and font choices made in Web Fonts aren't registered at fonts.com (and vice versa)
- installing fonts within my admin space at fonts.com only get registered in Web Fonts in some cases

## Don't know what might be the cause, but I'd sure like a cure...

**Comment by webfonts** [comment]
Hey Kames and Border,

The common issue I've seen is that the API key is wrong in your Joomla  
installation.  You can check this by logging into your Fonts.com account  
and seeing if the API key is the same as the one you have saved on your  
site's installation.  I don't know how this would get changed, but it will  
cause the behavior you described.  If you check and your API key matches,  
would you please contact me through the contact form on my website so that  
I can get admin credentials for your site and inspect for a possible bug?

Thanks,

John

From: BorderC notifications@github.com on Tue, 29 Jan 2013 23:11:32 +0900

> Hi KamesG, thanks for your comment. I'd really appreciate any advise I  
> can get, as I'am experiencing all sorts of issues with Web Fonts and  
> fonts.com. Basically, after working well in the past, something seems to  
> be wrong with the connection between my site and fonts.com. Experienced  
> issues are:
> - can't install new fonts from Web Fonts
> - selector and font choices made in Web Fonts aren't registered at  
>   fonts.com (and vice versa)
> - installing fonts within my admin space at fonts.com only get  
>   registered in Web Fonts in some cases
> 
> ## Don't know what's wrong, but I sure hope there is a cure.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/26#issuecomment-12836018

## 

John Hooley
Blue Bridge Development
(503) 893-9181
http://bluebridgedev.com

**Comment by webfonts** [comment]
This is not an authentication key problem, I'm looking into what might  
have changed in the environment to cause this behavior.

**Comment by webfonts** [comment]
I believe there might have been some changes in Fonts.com's API and have contacted them to see if there were any recent updates (because the extension hasn't changed.)  I'll post back here once we've figured this out.

**Comment by kamescg** [comment]
I ultimately just embedded the Fonts.com CSS & javascript into my Joomla Template.

Chances are it has something to do with the API, because I installed it earlier, logged in with the account and password, but uninstalled it because I thought I was going to take another route with the fonts.

When I installed the component again I tried the API this time. However, when I did used the API I could not search for fonts, let alone use them.

Another issue on the side is using fonts.com I am only able to select normal html tags like, but when I try to add the a class like .fontbold it doesn't get applied through out the website.

**Comment by webfonts** [comment]
I talked with my contact at Fonts.com and they told me that there was an API change, not a bug, but that they're going to modify it so that it will resolve this issue.

Regarding the .fontbold issue, can you email me through my sites contact form with a page where it is being applied and a page where it isn't?

bluebridgedev.com/contact

**Comment by BorderC** [comment]
Great news! Any idea when the change will be implemented?

**Comment by webfonts** [comment]
I'm not sure.  I received the message on Friday, but haven't seen any  
changes yet.  I'll post here as soon as I receive notice.

**Comment by webfonts** [comment]
This change has been implemented.

From: BorderC notifications@github.com on Mon, 04 Feb 2013 20:33:37 +0900

> Great news! Any idea when the change will be implemented?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/26#issuecomment-13072222

## 

John Hooley
Blue Bridge Development
(503) 893-9181
http://bluebridgedev.com

**Comment by BorderC** [comment]
Excellent. What a relief. Thanks for your dedicated support!
