### ISSUE TITLE
A little more instruction please?

### ISSUE THREAD

**Issue by johntennock** [webfonts/Web-Fonts#6]
I've followed all the instructions and selected a font from Google Webfonts. All very straightforward.

The fifth and final instruction in the documentation is:
1. Assign selectors to various fonts via the Stylesheet

I would greatly appreciate some guidance about just how to do this.

Thanks for a great extension. Looks really useful once I get past this limit in my knowledge.

**Comment by webfonts** [comment]
Hey John,

Thanks for trying Web Fonts.  The main screen in web fonts is the stylesheet screen.  It will load automatically when you open the Web Fonts component.  At that screen you can assign selectors and fallbacks to each font.  You can watch me do it on YouTube.  I start working on the stylesheet around 4:30:

http://www.youtube.com/watch?v=GCk91vAmBRI

Please note that, as the documentation and JED listing says, you need to have a base understanding of HTML and CSS to effectively use the extension because all fonts are implemented by assigning CSS selectors to html elements.  Firebug for Firefox is a great tool to determine which selectors need to be used to assign a font to an element.

Hope this is helpful,

John
