### ISSUE TITLE
Don´t work on local server (Xampp)

### ISSUE THREAD

**Issue by SNDK77** [webfonts/Web-Fonts#7]
I´m running webfonts on my server and works fine, but when I try to set it on Xampp don´t work.

When I try to <<add fonts>> on google show empty and in fonts.com show the login form but when I complete the form doesn´t show anything.

Thanks for the development, It´s very useful, shame con fonts.com for the ugly banner.

**Comment by SNDK77** [comment]
Correct in line 2, must say:  <Add Font>

**Comment by webfonts** [comment]
Hello,

I'm sorry to hear that you're having trouble using Web Fonts in your dev
environment.  Web Fonts makes use of the cURL extension for PHP.  I think
the reason it's not working in your environment is because you do not have
cURL installed/enabled.  I can't really help with this because this type of
tech support is not my forte (I haven't run XAMP in 5 years), but I did do
a search and found this:

http://stackoverflow.com/questions/3020049/how-to-enable-curl-in-xampp

I hope that helps!

Don't be too hard on the Fonts.com people, they are the only reason this
extension exists!  They hired me to do both their side and Google's side
and they provided many ideas for the layouts and also helped in getting it
built.  It's a big show of faith for them in open source and Joomla's
future because this type of development doesn't come cheap.  The banner is
removable with a commercial account ($10 a month), which is a good idea if
you build a lot of sites because font licenses can add up and also because
Fonts.com delivers fonts via their font delivery network which loads fonts
much faster than the other pretty font alternatives.

Sincerely,

John

On Tue, May 29, 2012 at 2:15 PM, SNDK77 <
reply@reply.github.com

> wrote:
> 
> I´m running webfonts on my server and works fine, but when I try to set it
> on Xampp don´t work.
> 
> When I try to <<add fonts>> on google show empty and in fonts.com show
> the login form but when I complete the form doesn´t show anything.
> 
> Thanks for the development, It´s very useful, shame con fonts.com for the
> ugly banner.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/7

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by SNDK77** [comment]
Sadly the CURL isn´t the problem. I follow the post you cite and don´t work.

This is my PHP info about Curl

curl
cURL support    enabled
cURL Information    7.21.7
Age     3
Features
AsynchDNS   Yes
Debug   No
GSS-Negotiate   Yes
IDN     No
IPv6    Yes
Largefile   Yes
NTLM    Yes
SPNEGO  No
SSL     Yes
SSPI    Yes
krb4    No
libz    Yes
CharConv    No
Protocols   dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp
Host    i386-pc-win32
SSL Version     OpenSSL/1.0.0e
ZLib Version    1.2.5
libSSH Version  libssh2/1.2.7 

I hope you can figure another reason about this issue, you are very kind.

In a second thought about Fonts.com they aren´t evil, instead the bet to open source and the development of extensions for joomla is a very good reason to trust they. 

Thanks.

**Comment by webfonts** [comment]
Hello,

Unfortunately, I don't know enough about XAMP to be of any help.  Two
things you might try are to see if there is any debugging information you
can turn on and also ask for help in the Joomla forums.  Though I don't
work with XAMP, I'm sure lots of other people do and might have better
advice about troubleshooting the differences between your development
environment and a production server.

Sorry I can't be of more help!

J

On Tue, Jun 5, 2012 at 11:27 AM, SNDK77 <
reply@reply.github.com

> wrote:
> 
> Sadly the CURL isn´t the problem. I follow the post you cite and don´t
> work.
> 
> This is my PHP info about Curl
> 
> curl
> cURL support    enabled
> cURL Information        7.21.7
> Age     3
> Features
> AsynchDNS       Yes
> Debug   No
> GSS-Negotiate   Yes
> IDN     No
> IPv6    Yes
> Largefile       Yes
> NTLM    Yes
> SPNEGO  No
> SSL     Yes
> SSPI    Yes
> krb4    No
> libz    Yes
> CharConv        No
> Protocols       dict, file, ftp, ftps, gopher, http, https, imap, imaps,
> ldap, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp
> Host    i386-pc-win32
> SSL Version     OpenSSL/1.0.0e
> ZLib Version    1.2.5
> libSSH Version  libssh2/1.2.7
> 
> I hope you can figure another reason about this issue, you are very kind.
> 
> In a second thought about Fonts.com they aren´t evil, instead the bet to
> open source and the development of extensions for joomla is a very good
> reason to trust they.
> 
> Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/7#issuecomment-6116321

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by Chacapamac** [comment]
Working here on MAMP — PHP Version 5.3.5 — Joomla 2.5.6 — Curl 7.21.3 enabled — Database Mysqli

PHP Built On    Darwin G4-867.local 8.11.0 Darwin Kernel Version 8.11.0: Wed Oct 10 18:26:00 PDT 2007; root:xnu-792.24.17~1/RELEASE_PPC Power Macintosh
Database Version    5.5.9
Database Collation  utf8_general_ci
PHP Version     5.3.5
Web Server  Apache/2.0.64 (Unix) PHP/5.3.5 DAV/2
WebServer to PHP Interface  apache2handler
Joomla! Version     Joomla! 2.5.6 Stable [ Ember ] 19-June-2012 14:00 GMT
Joomla! Platform Version    Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT
User Agent  Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.4; en-US; rv:1.9.2.28) Gecko/20120306 Firefox/3.6.28

**Comment by webfonts** [comment]
Thanks for posting your stats- it might provide a clue to someone who is having a similar problem to SNDK77 in their dev environment.
